# Generated by Django 2.0 on 2020-08-06 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calle', models.CharField(max_length=50)),
                ('Numero', models.IntegerField()),
                ('Piso', models.IntegerField(blank=True)),
                ('Complejo', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Cantidad', models.IntegerField()),
                ('Tipo_de_alimento', models.CharField(max_length=50)),
                ('Fecha_de_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Comida', models.ManyToManyField(to='PVUApp.Comida')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto', models.TextField(verbose_name='Introducir texto')),
                ('Fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observación_Psico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto', models.TextField(verbose_name='Introducir texto')),
                ('Fecha', models.DateField(auto_now=True)),
                ('Alergias', models.CharField(max_length=50)),
                ('Altura', models.CharField(max_length=50)),
                ('Peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nivel', models.CharField(choices=[('1', 'Admin'), ('2', 'Psicopedagogo'), ('3', 'Cocinero')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=True, help_text='Puede loggearse en esta página.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Quitar este parámetro en lugar de borrar cuentas', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Chico',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PVUApp.Persona')),
                ('Fecha_nacimiento', models.DateField()),
                ('Domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Domicilio')),
                ('Religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Religion')),
            ],
            bases=('PVUApp.persona',),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PVUApp.Persona')),
                ('Parentesco', models.CharField(choices=[('1', 'Padre'), ('2', 'Madre'), ('3', 'Tio'), ('4', 'Tia'), ('5', 'Hermano'), ('6', 'Primo'), ('7', 'Abuelo'), ('8', 'Abuela')], max_length=1)),
                ('Trabajo', models.CharField(max_length=50)),
                ('Chico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Chico')),
            ],
            bases=('PVUApp.persona',),
        ),
        migrations.AddField(
            model_name='observacion',
            name='Taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Taller'),
        ),
        migrations.AddField(
            model_name='comida',
            name='Ingrediente',
            field=models.ManyToManyField(to='PVUApp.Ingrediente'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='Taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Taller'),
        ),
        migrations.AddField(
            model_name='observación_psico',
            name='Chico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Chico'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='Chico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Chico'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='Chico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Chico'),
        ),
    ]
