# Generated by Django 2.0 on 2020-07-22 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Calle', models.CharField(max_length=50)),
                ('Numero', models.IntegerField()),
                ('Piso', models.IntegerField(blank=True)),
                ('Complejo', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Cantidad', models.IntegerField()),
                ('Tipo_de_alimento', models.CharField(max_length=50)),
                ('Fecha_de_vencimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
                ('Comida', models.ManyToManyField(to='PVUApp.Comida')),
            ],
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto', models.TextField(verbose_name='Introducir texto')),
                ('Fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observación_Psico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Texto', models.TextField(verbose_name='Introducir texto')),
                ('Fecha', models.DateField(auto_now=True)),
                ('Alergias', models.CharField(max_length=50)),
                ('Altura', models.CharField(max_length=50)),
                ('Peso', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PVUApp.Persona')),
                ('Correo_electronico', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
            ],
            bases=('PVUApp.persona',),
        ),
        migrations.CreateModel(
            name='Chico',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PVUApp.Persona')),
                ('Fecha_nacimiento', models.DateField()),
                ('Domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Domicilio')),
                ('Religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Religion')),
            ],
            bases=('PVUApp.persona',),
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PVUApp.Persona')),
                ('Parentesco', models.CharField(choices=[('1', 'Padre'), ('2', 'Madre'), ('3', 'Tio'), ('4', 'Tia'), ('5', 'Hermano'), ('6', 'Primo'), ('7', 'Abuelo'), ('8', 'Abuela')], max_length=1)),
                ('Trabajo', models.CharField(max_length=50)),
                ('Chico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Chico')),
            ],
            bases=('PVUApp.persona',),
        ),
        migrations.CreateModel(
            name='Psicopedagogo',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PVUApp.Persona')),
                ('Correo_electronico', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
            ],
            bases=('PVUApp.persona',),
        ),
        migrations.AddField(
            model_name='observacion',
            name='Taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Taller'),
        ),
        migrations.AddField(
            model_name='comida',
            name='Ingrediente',
            field=models.ManyToManyField(to='PVUApp.Ingrediente'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='Taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Taller'),
        ),
        migrations.AddField(
            model_name='observación_psico',
            name='Chico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Chico'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='Chico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Chico'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='Chico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Chico'),
        ),
    ]
