# Generated by Django 2.2.13 on 2020-08-19 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PVUApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Cantidad', models.IntegerField()),
                ('Medidas', models.CharField(choices=[('1', 'Kilos'), ('2', 'Gramos'), ('3', 'Litros')], max_length=1)),
                ('Fecha_de_vencimiento', models.DateField()),
                ('Enviado', models.BooleanField(default=False, help_text='Chequear cuando el alimento sea enviado', verbose_name='active')),
            ],
        ),
        migrations.CreateModel(
            name='Comedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Calle', models.CharField(max_length=50, null=True)),
                ('Numero', models.IntegerField(null=True)),
                ('Complejo', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Comedores',
            },
        ),
        migrations.CreateModel(
            name='Psico_chico',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='PVUApp.Persona')),
                ('Fecha_nacimiento', models.DateField()),
                ('Genero', models.CharField(choices=[('1', 'Masculino'), ('2', 'Femenino'), ('3', 'Otros')], default=1, max_length=1)),
            ],
            options={
                'verbose_name': 'Chico del programa de psicologia',
                'verbose_name_plural': 'Chicos del programa de psicologia',
            },
            bases=('PVUApp.persona',),
        ),
        migrations.AlterModelOptions(
            name='familiar',
            options={'verbose_name_plural': 'Familiares'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menús'},
        ),
        migrations.AlterModelOptions(
            name='observacion',
            options={'verbose_name_plural': 'Observaciones'},
        ),
        migrations.AlterModelOptions(
            name='observacionpsico',
            options={'verbose_name': 'Observaciones Psicologica', 'verbose_name_plural': 'Observaciones Psicologicas'},
        ),
        migrations.AlterModelOptions(
            name='taller',
            options={'verbose_name_plural': 'Talleres'},
        ),
        migrations.RemoveField(
            model_name='chico',
            name='Domicilio',
        ),
        migrations.RemoveField(
            model_name='chico',
            name='Religion',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='Ingrediente',
        ),
        migrations.AddField(
            model_name='chico',
            name='Genero',
            field=models.CharField(choices=[('1', 'Masculino'), ('2', 'Femenino'), ('3', 'Otros')], default=1, max_length=1),
        ),
        migrations.DeleteModel(
            name='Domicilio',
        ),
        migrations.DeleteModel(
            name='Ingrediente',
        ),
        migrations.DeleteModel(
            name='Religion',
        ),
        migrations.AddField(
            model_name='psico_chico',
            name='Chico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Chico', verbose_name='En caso de ser un chico de un comerdor ya existente'),
        ),
        migrations.AddField(
            model_name='alimento',
            name='Comedor_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Comedor'),
        ),
        migrations.AddField(
            model_name='chico',
            name='Comedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Comedor'),
        ),
        migrations.AddField(
            model_name='familiar',
            name='Psico_chico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Psico_chico'),
        ),
    ]
