# Generated by Django 2.0 on 2020-08-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVUApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='apellido',
            field=models.CharField(default='asdas', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myuser',
            name='nombre',
            field=models.CharField(default='asdasdsa', max_length=50),
            preserve_default=False,
        ),
    ]
