# Generated by Django 2.2.13 on 2020-11-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PVUApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacion_psico',
            name='chico_psico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PVUApp.Psico_chico'),
        ),
    ]
